org: alissonhonostorio
app: sweet-mommy
service: sweet-mommy

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-tscpaths

functions:
  Register:
    handler: src/useCases/register/handler.default
    events:
      - httpApi:
          method: POST
          path: /register

custom:
  tscpaths:
    buildPath: .build
    tsconfigPath: tsconfig.json
